name: RedTeam
favicon: null
layout_spectrum: 0.29801244009286165
typography_spectrum: 0.6908158254809678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d50a19'
    - '#545859'
    - '#f4ccc5'
    - '#858585'
  brandStrength: 0.5
  lightness: 0.8478672029450536
  saturation: 0.9241361902095377
  rhythmicContrast: 0.9242091882042587
purpose: []
