name: RedTeam
favicon: null
layout_spectrum: 0.14764
typography_spectrum: 0.11455
title: 'Rebuilding Environments by Design '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#34343c'
    - '#b9010b'
    - '#c4c4c4'
    - '#656567'
  brandStrength: 0.6875
  lightness: 0.8478672029450536
  saturation: 0.9241361902095377
  rhythmicContrast: 0.9242091882042587
purpose: []
